'use strict';
const variants=['cleaned_recent','raw_ocr_recent','screenshots_recent'];
const names={cleaned_recent:'Expanded cleaned text',raw_ocr_recent:'Expanded full-window raw OCR',screenshots_recent:'Original screenshots · reused'};
const oldNames={cleaned_recent:'Original cleaned text',raw_ocr_recent:'Original recent raw OCR + older cleaned history'};
const $=id=>document.getElementById(id);
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
let all=[],visible=[],current=null,frame=0,loadID=0,contextID=0;
async function get(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(`Unable to load (${r.status})`);return r.json();}
function error(e){$('error').textContent=e.message;}
function filter(){const mode=$('filter').value,q=$('search').value.trim().toLowerCase();visible=all.filter(c=>{const [a,b,d]=variants.map(v=>c.passes[v]),oa=c.originalPasses.cleaned_recent,ob=c.originalPasses.raw_ocr_recent;return(!q||String(c.case)===q||c.target.toLowerCase().includes(q))&&({all:true,clean_gain:!oa&&a,clean_loss:oa&&!a,raw_gain:!ob&&b,raw_loss:ob&&!b,image_only:d&&!a&&!b,text_only:!d&&(a||b)}[mode]);});$('cases').replaceChildren(...visible.map(c=>{const o=el('option',`#${c.case} · ${c.application} · ${c.target.slice(0,55)}`);o.value=c.case;return o;}));if(!visible.length){$('case').hidden=true;$('position').textContent='No matching cases';$('prev').disabled=$('next').disabled=true;return;}const n=visible.some(c=>c.case===current?.case)?current.case:visible[0].case;$('cases').value=n;show(n).catch(error);}
function card(c,v,old=false){const r=(old?c.originalAnswers:c.answers)[v],a=el('article',undefined,'answer'),head=el('div',undefined,'row');head.append(el('h3',(old?oldNames:names)[v]),el('span',r.semanticPass?'PASS':'FAIL',`grade ${r.semanticPass?'pass':'fail'}`));a.append(head,el('pre',r.prediction),el('p',r.reason),el('p',`${r.inputTokens.toLocaleString()} input tokens · ${r.timing.dispatchToCompletionSeconds.toFixed(1)}s · $${r.apiEquivalentCostUSD.toFixed(3)} API-equivalent`,'metrics'));
 if(!old&&v!=='screenshots_recent'){const b=c.budgets[v];a.append(el('p',`Budget ${b.assignedInputTokens.toLocaleString()} tokens · history span ${(b.expandedHistorySpanSeconds/60).toFixed(1)} min (wall-clock, not active reading)`,'metrics'));}if(!old&&v==='screenshots_recent')a.append(el('p','Same original answer and grade. No new screenshot request.','metrics'));const b=el('button','Inspect exact supplied context');b.onclick=()=>context(c.case,v,old).catch(error);a.append(b);return a;}
async function show(n){const id=++loadID;++contextID;$('case').hidden=true;$('context').hidden=true;$('error').textContent='';const c=await get(`/api/case/${n}`);if(id!==loadID)return;current=c;frame=0;history.replaceState(null,'',`#${n}`);$('case').hidden=false;$('heading').textContent=`Case ${n}`;$('meta').textContent=`${c.query.destination.application} · ${c.beganAt}`;$('target').textContent=c.target;$('query').textContent=JSON.stringify(c.query,null,2);$('answers').replaceChildren(...variants.map(v=>card(c,v)));$('original').replaceChildren(...variants.slice(0,2).map(v=>card(c,v,true)));$('frame-title').textContent=`${c.frames.length} original screenshots · captured before this WRITE`;$('interval').textContent=`Original image interval: ${c.interval.startAt} → ${c.interval.latestFrameAt}. The screenshot arm retains its original older cleaned background; the two expanded text arms cover different spans.`;$('frame-index').max=Math.max(0,c.frames.length-1);$('frame-index').value=0;$('frame-image').removeAttribute('src');if($('screenshots').open)showFrame();const i=visible.findIndex(x=>x.case===n);$('position').textContent=`${i+1} / ${visible.length}`;$('prev').disabled=i===0;$('next').disabled=i===visible.length-1;}
async function context(n,v,old){const id=++contextID,p=await get(`/api/${old?'original-context':'context'}/${n}/${v}`);if(id!==contextID||current?.case!==n)return;$('context-title').textContent=`${(old?oldNames:names)[v]} · exact input`;$('context-text').textContent=p.parts.map(t=>t.type==='image'?`[Original screenshot ${t.imageIndex+1}, shown below]`:t.text).join('\n\n');$('context').hidden=false;$('context').scrollIntoView({block:'start'});}
function showFrame(){if(!current?.frames.length)return;frame=Math.max(0,Math.min(frame,current.frames.length-1));const f=current.frames[frame];$('frame-index').value=frame;$('frame-meta').textContent=`${frame+1}/${current.frames.length} · ${f.capturedAt||''} · ${f.source?.application||''}`;$('frame-image').src=f.url;$('frame-full').href=f.url;$('frame-prev').disabled=frame===0;$('frame-next').disabled=frame===current.frames.length-1;}
function move(d){const i=visible.findIndex(c=>c.case===current?.case)+d;if(i>=0&&i<visible.length){$('cases').value=visible[i].case;show(visible[i].case).catch(error);}}
$('filter').onchange=filter;$('search').oninput=filter;$('cases').onchange=()=>show(Number($('cases').value)).catch(error);$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('close-context').onclick=()=>{$('context').hidden=true;++contextID;};$('screenshots').ontoggle=()=>{if($('screenshots').open)showFrame();};$('frame-prev').onclick=()=>{frame--;showFrame();};$('frame-next').onclick=()=>{frame++;showFrame();};$('frame-index').oninput=()=>{frame=Number($('frame-index').value);showFrame();};
get('/api/overview').then(d=>{all=d.cases;const table=el('table'),head=el('tr');['Representation','Passes','Mean input tokens','Median latency','API-equivalent / query'].forEach(t=>head.append(el('th',t)));table.append(head);for(const [label,a] of [[oldNames.cleaned_recent,d.summary.original.arms.cleaned_recent],[names.cleaned_recent,d.summary.arms.cleaned_recent],[oldNames.raw_ocr_recent,d.summary.original.arms.raw_ocr_recent],[names.raw_ocr_recent,d.summary.arms.raw_ocr_recent],[names.screenshots_recent,d.summary.arms.screenshots_recent]]){const row=el('tr');[label,`${a.passes}/69 · ${(100*a.passRate).toFixed(1)}%`,Math.round(a.inputTokens.mean).toLocaleString(),`${a.latencySeconds.median.toFixed(1)}s`,`$${a.apiEquivalentUSD.mean.toFixed(3)}`].forEach(t=>row.append(el('td',t)));table.append(row);}$('summary').replaceChildren(table);$('authority').textContent='Intention-level judgments, not exact-match scoring. Two assistant reviews with reconciliation; original grades preserved. Construction quality is audited separately. All dollar values are API equivalents, not subscription charges. Selected diagnostic cohort; one answer per condition.';const n=Number(location.hash.slice(1));if(all.some(c=>c.case===n))current={case:n};filter();}).catch(error);
